server {

    listen 80;
    server_name _;

    return 301 https://57.156.66.202:8443$request_uri;
}

server {

    listen 8443 ssl;

    server_name _;

    ssl_certificate     /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;

    ssl_protocols TLSv1.2 TLSv1.3;

    root /usr/share/nginx/html;

    index index.html;

    auth_basic "Caso Practico 2";

    auth_basic_user_file /etc/nginx/certs/.htpasswd;

    location / {

        try_files $uri $uri/ =404;

    }

}
